name: "20 CD Pipeline"
on:
  workflow_dispatch:
    inputs:
      ci_run_id:
        description: "Run ID of the CI pipeline run to reference the Docker image and Terraform artifacts."
        required: true

jobs:
  test:
    runs-on: ubuntu-24.04
    # if: false # Temporarely disabling this job to work on something else instead
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Use custom Terraform provision action"
        id: terraform-provision
        uses: ./.github/actions/terraform-provision
        with:
          tf_api_token: ${{ secrets.TF_API_TOKEN }}
          workspace: test
          varfile: "values/test.tfvars"
          docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.event.inputs.ci_run_id }}

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: "${{ steps.terraform-provision.outputs.app_fqdn }}"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  prod:
    runs-on: ubuntu-24.04
    needs: test
    # if: false # Temporarely disabling this job to work on something else instead
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Use custom Terraform provision action"
        uses: ./.github/actions/terraform-provision
        with:
          tf_api_token: ${{ secrets.TF_API_TOKEN }}
          workspace: prod
          varfile: "values/prod.tfvars"
          docker_image: ${{ vars.DOCKER_HUB_USERNAME }}/juice-shop:${{ github.event.inputs.ci_run_id }}