name: "CI Pipeline"

on:
  push:
    branches:
      - master # Trigger CI pipeline only for changes pushed to the master branch
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the repository
      - name: "Checkout code"
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using credentials stored in GitHub secrets
      - name: "Log into Docker Hub"
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      # Step 3: Build the Docker image for the application
      - name: "Build agondo App Docker image"
        run: docker build -t juice-shop:${{ github.run_id }} .

      # Step 4: Install Docker Scout for security scanning
      - name: "Install Docker Scout"
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      # Step 5: Scan the Docker image for CVEs using Docker Scout
      - name: "Scan Docker image with Docker Scout"
        run: docker scout cves juice-shop:${{ github.run_id }}

      # Step 6: Verify SonarCloud Project Configuration
    
      - name: "Verify SonarCloud Project Configuration"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      run: |
        curl -u "${SONAR_TOKEN}:" \
        "https://sonarcloud.io/api/projects/search?projects=${SONAR_PROJECT_KEY}"

       