name: "CI Pipeline"

on:
  push:
    branches:
      - master # Trigger CI pipeline only for changes pushed to the master branch
  workflow_dispatch: # Allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the repository
      - name: "Checkout code"
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using credentials stored in GitHub secrets
      - name: "Log into Docker Hub"
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: echo "${DOCKER_HUB_PASSWORD}" | docker login -u "${DOCKER_HUB_USERNAME}" --password-stdin

      # Step 3: Build the Docker image for the application
      - name: "Build agondo App Docker image"
        run: docker build -t juice-shop:${{ github.run_id }} .

      # Step 4: Install Docker Scout for security scanning
      - name: "Install Docker Scout"
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh

      # Step 5: Scan the Docker image for CVEs using Docker Scout
      - name: "Scan Docker image with Docker Scout"
        run: docker scout cves juice-shop:${{ github.run_id }}

      # Step 6: Verify SonarCloud Project Configuration
      - name: "Verify SonarCloud Project Configuration"
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/projects/search?projects=${{ secrets.SONAR_PROJECT_KEY }}"

      # Step 7: Run a SonarCloud scan for code analysis
      - name: "SonarCloud Scan"
        uses: SonarSource/sonarqube-scan-action@v4.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=master
            -X
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=.
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
