name: "CI Pipeline"

on:
  push:
    branches:
      - master
  workflow_dispatch: # allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Build Docker image"
        run: docker build -t juice-shop:${{ github.run_id }} .

      - name: "Log into Docker Hub"
        run: echo "Aglagtin1$" | docker login -u "agondo69" --password-stdin

      - name: "Push image to DockerHub"
        run: docker push juice-shop:${{ github.run_id }}

